name: Catinder
description: Cat Tinder

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  get_it: ^7.2.0
  http: ^1.2.0
  ntp: ^2.0.0
  cached_network_image: ^3.3.1
  share_plus: ^10.1.4
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.5.2
  equatable: ^2.0.5
  flutter_card_swiper: ^7.0.2
  connectivity_plus: ^4.0.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
    - assets/images/cat_heart2.png
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_launcher_icons:
  android: "assets/icon/app_icon.png"
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_foreground: "assets/icon/app_icon.png"